package code
package model

import net.liftweb.mapper._
import net.liftweb.util._
import net.liftweb.common._


class Event extends KeyedMapper[String, Event] {
  def getSingleton = Event
  def primaryKeyField = name

  object name extends MappedStringIndex(this, 50)  {
    //override def dbAutogenerated_? = false
    override def dbNotNull_? = true
  }
  object data extends MappedTextarea(this, 1000)
  object saveDate extends MappedDateTime(this)
}

object Event extends Event with KeyedMetaMapper[String, Event] {
  override def fieldOrder = List(data)
}
